use_frameworks!

target 'Birdsong_Example' do
  pod 'Birdsong', :path => '../'
  pod 'Starscream', git: 'https://github.com/daltoniam/Starscream.git', branch: 'swift3'

  target 'Birdsong_Tests' do
    inherit! :search_paths
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        puts "[post install] " << target.name << ":" << config.name << " set SWIFT_VERSION to 3.0"
        config.build_settings['SWIFT_VERSION'] = '3.0'
      end
    end
  end
end
